name: r2gapi_flutter_sdk
version: 1.0.0
description: Ride2Go API SDK for Flutter. Built with Dio.
environment:
    sdk: ">=2.3.0 <3.0.0"
dependencies:
    flutter:
        sdk: flutter

    dio: ^3.0.4
    dio_flutter_transformer: ^3.0.2
    built_value: ^6.8.2
    built_collection: ^4.2.2
dev_dependencies:
    built_value_generator: ^6.8.2
    build_runner: ^1.7.1
    test: 1.6.5
